### ISSUE TITLE
initialisation not working

### ISSUE THREAD

**Issue by sebhaan** [Sydney-Informatics-Hub/eeharvest#3]
README example results in:

EEException: Earth Engine client library not initialized. Run `ee.Initialize()`

alternative:
"""
from eeharvest import harvester
harvester.initialise()
"""
AttributeError: module 'eeharvest.harvester' has no attribute 'initialise'

**Comment by januarharianto** [comment]
Fixed.

Update `eeharvest`

```zsh
pip install eeharvest -U
```

Then this should work:

```py
from eeharvest import harvester
harvester.initialise()
```
